language: python
python:
- '3.6'
install:
- pip install .
script:
- python setup.py test
deploy:
  provider: pypi
  user: pdepaepe
  password:
    secure: jtHB2pqwI7ybEQx/r4n7Gl7uhJ1kbM+8EyNbIodd3aAUJWl+ncVD7hDkYykP3pxyQK73PPk+tlo+D3II6p9vNWW3GZZIKtmssvNM8gkTP0l7ROcegUrRiygA5fxlI2vpbq5g/9+lAejKczGvadJBj/x8qE3ZH93Vy1LfYDQ4QA+V3z030cELgPwXS22OB88Ca/Cb588BJiGqUyZlyw62pHRpu+aMrE8f7HBaUu/ePJNrMmnSJ1sah+KLtumpfAdhBRBzLNiUnHlWIRmMgct2Z2+buAJrS1XEtDEVZ6MYEfxE4Oa426qI5Rg1v/l4Az/Rd+h6V5bSBwHYz9LYw5mRMnNsZI2akVVZ/lW5hogiYHhihc1CSIp8/e7ItI3IoiQFOT0y94ONTUwatgYY5qJpOnX9PkaHDYpi2mzT+Xi43LeifJLhuBWt6wADrJqlWEEcE+zEbH+zh36nbpiPz9+xyv7F4r/lUAfyTynfaNmftQm4kKWUuW3OQUzUwEq6bN49BBLQiOqtXoyXSCO3VHG32yix9XjeqLdnH56ANYQlZ4bN471e7MB9bKK0d+1CMoYGxeYAloemncSyo3SOeuBxvhCgs8B2A3+MLYt54WemitKw2+srSC4hS0gGdN0f6gdclMnc/XBswU1seFXExVlHTlEEnQmBllc2zXBNZYZnk00=
  on:
    tags: true
    repo: ovh/ldp-archive-mirror
